//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp2007_Assignment2_Nicholls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Number { get; set; }
        public string Name { get; set; }
        public string Descrip { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
